server:
  port: 5051

spring:
  application:
    name: ArticoliWebService
  #==========================================================
  #= PARAMETRI DBMS POSTGRESQL
  #==========================================================
  sql:
    init:
      mode: always
      platform: postgres
  datasource:
    password: root
    platfirm: postgres
    url: jdbc:postgresql://localhost:5433/AlphaShop
    username: postgres
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none # disattivo ddl cosi non posso modificare la struttura creando un database, ma lo creo direttamente io
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

    #==========================================================
    #= OPZIONI DI ACCESSO AL MICROSERVIZIO GESTUSER
    #= url di riferimento dell'end point con il quale otteniamo le specifiche dell'utente
    #= utente di base ReadUser e password, questi parametri saranno ottenuti nella classe userConfig
    #==========================================================
    # BimBumBam_2018 è presente come endpoint in file securityconfig del microservizio gestuser
  gestuser:
    srvUrl: http://localhost:8019/api/utenti/cerca/userId/
    userId: ReadUser
    password: BimBumBam_2018