#==========================================================
#= GestUser Web Service - Versione Base
#==========================================================

server:
  port: 8019
spring:
  application:
    name: GestUser
  #==========================================================
  #= PARAMETRI DB MONGODB

  # c'è l'autentication db che è admin, use admin poi ora
  #uso mongo -u admin --authenticationDatabase admin -p root e mi autentico come admin nome admin
  # ora creo user condb.createUser({
  #    user:"pippo",
  #    pwd:"D3mondante.@",
  #    roles:[{ role: "readWrite", db: "ms-users"  }]
  #})
  #poi ora switcho mettendo nome e pass di questo utente
  #mongo -u pippo--authenticationDatabase admin -p D3mondante.@
  #ora  che sono nel nuovo utente uso
  # use ms-users per spostarmi nel db del nuovo utente
  # qui o creo le mie query o permetto tramite file yml a spring di farlo!!!
  #==========================================================
  data:
    mongodb:
      authentication-database: admin
      database: ms-users
      host: localhost
      password: D3mondante.@
      port: 37017
      username: pippo
      auto-index-creation: true

      ################################REDJWT###############################
  jwt:
    header: Authorization
    # This token must be encoded using Base64 with mininum 88 Bits (you can type echo 'secret-key'|base64 on your command line)
    #checked
    jwtSecret: Wm1RMFpHSTVOalEwTURRd1kySTRNak14WTJZM1ptSTNNamRoTjJabU1qTmhPRFZpT1RnMVpHRTBOVEJqTUdNNE5EQTVOell4TWpkak9XTXdZV1JtWlRCbFpqbGhOR1kzWlRnNFkyVTNZVEUxT0RWa1pEVTVZMlkzT0dZd1pXRTFOelV6TldRMllqRmpaRGMwTkdNeFpXVTJNbVEzTWpZMU56Sm1OVEUwTXpJPQo=
    # token is valid 12 hours
    jwtExpirationMs: 5000000
      # valid 20 hours
      #token-validity-in-seconds-for-remember-me: 88000
    #route:
    # authentication:
    #  path: auth
    #  refresh: refresh