#==========================================================
#= GestUser Web Service - Versione Base
#==========================================================

server:
  port: 8019
spring:
  application:
    name: GestUser
    datasource:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/myDb
      username: user1
      password: pass
#==========================================================
#= PARAMETRI DB MONGODB 
#==========================================================
  data:
    mongodb:
      authentication-database: admin
      database: ms-users
      host: localhost
      password: d3mondante
      port: 37017
      username: souhail
      auto-index-creation: true
